### ISSUE TITLE
Events are not being stored in table `event_stream`

### ISSUE THREAD

**Issue by josecelano** [prooph/laravel-package#10]
Hi:

I have some events and listeners. The listeners are being called and the `event_stream` table exists but the events are not being inserted in the table.

**Comment by sandrokeil** [comment]
Do you get any errors or exceptions? Please check your [respository configuration](https://github.com/prooph/proophessor-do/blob/master/config/autoload/prooph.global.php#L35). The event store writes the stream. The event bus is only for projections (read model). You have to [save your aggregate](https://github.com/prooph/proophessor-do/blob/master/src/Model/User/Handler/RegisterUserHandler.php#L45) via the [repository](https://github.com/prooph/proophessor-do/blob/master/src/Infrastructure/Repository/EventStoreUserCollection.php). I hope this helps.

**Comment by josecelano** [comment]
Hey thank @sandrokeil I am not using AggregateRepository, I am only using the ServiceBus. I thougth all events were stored in the event store, even those event which have been injected in the event bus by a command handler. In my command handler I have somethiing like:

`$this->eventBus->dispatch($projectWasCreated);`

Is there a way (some middleware maybe) to store this kind of events? Should I use the same table?
I want a log of all events which have been injected inthe event bus. I could add an event dispachter in my app and persist event before injecting the in the bus but I supposed I can do that with this library.

I do not want to use do EventSourcing for the time being, I am only using comand and events.

**Comment by sandrokeil** [comment]
That's totally fine. You can use it independent. I guess you have to write a [plugin](http://getprooph.org/service-bus/plugins.html#2.4) and put it to the event bus. Choose one of [this events](https://github.com/prooph/service-bus/blob/master/src/MessageBus.php#L32) which fits your needs.
