### ISSUE TITLE
Is really doctrine required? Can MongoDB be an option?

### ISSUE THREAD

**Issue by dranzd** [prooph/laravel-package#11]
We are using prooph components for our project that uses CQRS + ES and decided to use MongoDB for the Event Store.  Our group also decided to use Laravel and found this package that may simplify the configuration.  But one of the components required by this package is the Doctrine adapter for the EventStore.

This is the first time I'm going to use the laravel so I am not sure if MongoDB is not supported, maybe that's the reason why Doctrine is required?  If MongoDB is allowed to be used on Laravel, why is it that the Doctrine adapter is required?  Isn't it supposed to be an option?

**Comment by codeliner** [comment]
Hey @dranzd , see the readme of the package: https://github.com/prooph/laravel-package#overview

Atm it is only a quick start package with doctrine DBAL configured as default adapter. You can of course use the mongoDb adapter with Laravel but you have to integrate it yourself. However, this package can give you an idea how you achieve prooph integration in Laravel. In the future we will support mongoDb with this package. But we need to do some other work first.

**Comment by dranzd** [comment]
Thanks @codeliner.  We've decided to use the Doctrine and see how it works for now.  Will integrate MongoDb once we have it working.  This project is more like an experimentation for us to learn how to integrate all necessary parts.  Thanks for all these packages that you and others have shared!
