### ISSUE TITLE
Make use of Laravel's facade pattern.

### ISSUE THREAD

**Issue by bweston92** [prooph/laravel-package#15]
# Facades

The following facades will be supported out of the box for prooph's Laravel package. These facades will map to the corresponding buses.

- CommandBus
- EventBus
- QueryBus

# Additional Features

- Allow for methods on a query to return the real value. For example `QueryBus::resultFrom($aQuery)` would return either throw exception or the return the result.

# Definition of Done

- [x] We have all 3 facades working just by adding the "service provider".
- [x] We have appropriate tests in place.
- [x] There is an example for each use case in a new directory `/examples`.
- [x] A stub class that will make IDEs auto complete for all facades.

**Comment by codeliner** [comment]
nice :+1:

**Comment by bweston92** [comment]
@codeliner anything you want to add or will this be ok for a 0.4 release?

**Comment by codeliner** [comment]
support for event-store v7 and service-bus v6 ? We should check if something needs to be aligned

**Comment by bweston92** [comment]
are you saying to drop support for earlier versions of them packages or handle both of them?

**Comment by codeliner** [comment]
I'd say drop or at least no new features for old package versions. You added the container wrapper so that the integration works again that should be enough for the old versions of event-store and service-bus.

If the facades work for old versions, too. Well then it's a nice addition ;)
