### ISSUE TITLE
Upgrade to latest prooph components.

### ISSUE THREAD

**Issue by bweston92** [prooph/laravel-package#17]
Cannot currently install this package on Laravel 5.4 do to issues with version constraints, after I modified a local version to use latest prooph components it worked.

Need to collect information about configuration changes. Proposed component constraints below:
```
-     "prooph/event-sourcing": "^4.0",
+     "prooph/event-sourcing": "^5.0",
-     "prooph/event-store": "^6.0",
+     "prooph/event-store": "^7.0",
-     "prooph/service-bus": "^5.0.2",
+     "prooph/service-bus": "^6.0",
```

Requirements:
- [x] Update interop-config to v2 required by latest prooph components.
- [x] Update dependencies in the Composer requirements.
- [ ] Update default configuration for event store.
- [ ] Update default configuration for service bus.

**Comment by bweston92** [comment]
@codeliner can you provide a brief overview of configuration changes?
@sandrokeil can you upgrade the interop-config package and apply any changes required?

**Comment by codeliner** [comment]
@bweston92 I'm on vacation the next days. Configuration changes shouldn't be that much. Did you already take a look at the diff of prooph-do (I guess @prolic suggested it some days ago in the chat)?
- the event store config did change 
    - from: one store + an adapter
    - to: vendor specific event-store that might be wrapped with an ActionEventEmittingEventStore so that event store plugins can be attached via configuration

@prooph/symfony-team deal with the same set of changes at the moment in the symfony bundle. Maybe we should group together to identify problems and find solutions. I'm back end of next week. Please ping me if I should provide more infos or look at a problem.

**Comment by sandrokeil** [comment]
@bweston92 Will do. Has anyone already started? So I can bring a PR next week?

**Comment by sandrokeil** [comment]
@bweston92 Should we increase minimum Laravel version too?

**Comment by sandrokeil** [comment]
@bweston92 Can I rebase this branch with master, so we have the latest changes here?

**Comment by bweston92** [comment]
Sure

**Comment by codeliner** [comment]
Can we close the issue or is still something left?
