### ISSUE TITLE
Interop laravel-container service missing

### ISSUE THREAD

**Issue by lezhnev74** [prooph/laravel-package#19]
Hey, guys! 
Just start playing with Prooph with Laravel and tried to follow the installation instructions:

https://github.com/monii/monii-container-interop-laravel - this package is absent but it says I need to add the service provider:
```
In your application configuration add Monii\Interop\Container\Laravel\ServiceProvider for container-interop support
```

I'll try to find ways to solve this but so far I was not able to run my code:

```
$command = new ReportLogCommand();
$commandBus = app(CommandBus::class);
$commandBus->dispatch($command);
```

Any ideas where to go from here?

**Comment by lezhnev74** [comment]
Further investigation showed that problem is in the LaravelContainer.php:

there is a function declared to return bool, but nothing returned:
```
private function cacheHas(string $id, bool $has): bool
    {
        $this->cacheForHas[$id] = $has;
    }
```

**Comment by lezhnev74** [comment]
I wonder if you plan to integrate Laravel's queue feature with Prooph's async command handling feature. Is it something in the backlog or you need a hand to make it happen?

**Comment by codeliner** [comment]
@lezhnev74 we need more helping hands for Laravel integration. If you have some spare time would be nice to see some more PRs from you ;). @bweston92 started to work on updating the package recently. He removed monii-container dependency, so docs are outdated and need some update.
Supporting Laravel's queue feature is a great idea. Nice if you can start working on it. If you have more ideas to improve Laravel prooph experience just open an issue and we can discuss it.

I keep this issue open until docs are updated, too

**Comment by codeliner** [comment]
ok [v0.4](https://github.com/prooph/laravel-package/releases/tag/v0.4) is available so we can close this one.
