### ISSUE TITLE
QueryBus with FinalizeGuard enabled returns null

### ISSUE THREAD

**Issue by lezhnev74** [prooph/laravel-package#24]
Hi, I am lost with `FinalizeGuard` and how to set it up properly. I am not sure if this relates to Laravel package or to MessageBus core.

1. I have my query and corresponding finder. On success it resolves Deferred like this:

```php
class QueryFinder {
    function __invoke($query, Deferred $deferred = null): void
    {
        //...
        $deferred->resolve($query_result);
    }
}
```

2. I enabled `FinalizeGuard` in prooph.php config file.

3. But the result of the query returns null.

```php
// I use facade
$query_result = QueryBus::resultFrom($query);
// $query_result is null now
```

4. If I disable the `FinalizeGuard` then query returns valid result. So it led me into looking inside of the `FinalizeGuard` code.

5. Looking at 48 line: https://github.com/prooph/service-bus/blob/c239acfd43cf8eec577e30ce0aa7da86d87b6191/src/Plugin/Guard/FinalizeGuard.php#L48
It creates a new Promise and here it losts resolved result. 

It seems that I misuse QueryBus. Can you suggest the right way of resolving Deferred object inside my QueryFinder which works with FinalizeGuard?

**Comment by basz** [comment]
> It seems that I misuse QueryBus

Why you think you misuse the query bus?

```
$this->queryBus
            ->dispatch(
                (new GetCustomer(['customer_id' => ...]))
            )
            ->done(function (QueryResult $result) use (&$dto) {
                $dto = $result->data();
            });
```

This works for me with FinalizeGuard enabled

**Comment by lezhnev74** [comment]
Hmm, can you show how you resolve deferred promise inside the finder class?

**Comment by basz** [comment]
```
    public function getCustomer(GetCustomer $query, Deferred $deferred): void
    {
        /** @var Customer $customer */
        if ($customer = $this->entityManager->getRepository(Customer::class)->find($query->customerId())) {
            $customerDTO = CustomerDTO::fromEntity($customer, $query->included());

            $deferred->resolve(JsonApiQueryResult::with($customerDTO, [], new EncodingParameters($query->included())));
        } else {
            $deferred->reject(new DomainException('Not found', 404));
        }
    }
```

**Comment by lezhnev74** [comment]
Ok, the problem persists.
I have created a new project from scratch with laravel-package: https://github.com/lezhnev74/prooph-query-test

1. I have installed prooph and configured it here: https://github.com/lezhnev74/prooph-query-test/blob/master/config/prooph.php
2. If I comment out the line 45 tests pass, if I uncomment it, tests fail:
```
45: \Prooph\ServiceBus\Plugin\Guard\FinalizeGuard::class
```
3. This test runs a query and validates result is not null:
https://github.com/lezhnev74/prooph-query-test/blob/master/tests/Component/Account/Query/FindAccountByEmail/FindAccountByEmailHandlerTest.php
it can be run like this: `vendor/bin/phpunit --testsuite=Components`


Can you tell if I configured prooph wrong or something is not right? 
Composer says I have these versions:
```
prooph/common                         v4.2.1  Common classes used across prooph packages
prooph/event-sourcing                 v5.3.0  PHP EventSourcing library
prooph/event-store                    v7.3.1  PHP EventStore Implementation
prooph/event-store-bus-bridge         v3.1.0  Marry CQRS with Event Sourcing
prooph/laravel-package                v0.4    Laravel package for prooph components to get started out of the box with message bus, CQRS, event sou...
prooph/pdo-event-store                v1.6.0  Prooph PDO EventStore
prooph/pdo-snapshot-store             v1.4.0  PDO Snapshot Store Implementation
prooph/service-bus                    v6.2.0  PHP Enterprise Service Bus Implementation supporting CQRS and DDD
prooph/snapshot-store                 v1.3.0  Prooph Snapshot Store
```

P.s. I use a standalone router which maps directly command(query) to it's handler so routes config is empty.

P.p.s I will try to install prooph fresh with no laravel dependency and try it in another branch of that repo.

**Comment by lezhnev74** [comment]
I have removed everything and included just bare message bus and implemented this test: 
https://github.com/lezhnev74/prooph-query-test/blob/prooph-bare/tests/QueryTest.php

It has 3 tests:
- executing query with no guards [pass]
- executing query with RouteGuard [pass]
- executing query with FinalizeGuard [fail]

Hmm, why does it fail in the last test?

**Comment by lezhnev74** [comment]
This is not about Laravel packag I'd say, so I am closing this issue.
The issue in message bus hub: https://github.com/prooph/service-bus/issues/177
