### ISSUE TITLE
ServiceProvider auto-discovery not published

### ISSUE THREAD

**Issue by jankal** [prooph/laravel-package#26]
Current `0.4` does not include e9647921ad1dc7b9753010e4648933555d89cddc (which added package auto-discovery) although ServiceProvider auto-discovery is outlined in `README` of master. New users of the package will expect this to work when reading the `README`. But it doesn't.

It would be nice to have something like a `0.4.1` tag with the relevant commit included.

**Comment by bweston92** [comment]
Hi @jankal that has now been done, any issues please reopen the issue.
